spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/coconoon?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    password: 1234
    username: root
  #rudflxla12 admin 1234
  mail:
    host: smtp.gmail.com
    port: 587
    username: 00woogi@gmail.com
    password: fnql1234!
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 918079045792-2t4t5dqtdfgdj75d6vqshnuj3jm6lrr3.apps.googleusercontent.com
            client-secret: q5dRwKeubnhuXtsK55uF7PWc
            scope: profile, email

logging:
  config: classpath:log4j2.yml

kakao:
      js: abb0c5392e88307fec21ccc5d3ef776a

