spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: rudflxla12
    url: jdbc:mysql://localhost:3306/coconoon?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: root
  // rudflxla12 admin 1234

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: 00woogi@gmail.com
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true